services:
  backend:
    build:
      context: ./Backend
    container_name: app-backend
    ports:
      - "4000:8080"

  frontend:
    build:
      context: ./front
    container_name: app-frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
